// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UiDesktopApp2.DataAccess;

#nullable disable

namespace UiDesktopApp2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250304174034_imageset_order")]
    partial class imageset_order
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ImageSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUknown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("ImageSets");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ImageVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageSetId");

                    b.ToTable("ImageVariants");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvailableTimePerImageVariant")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TestId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ResultImageSetTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Seconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ImageSetId");

                    b.HasIndex("ResultId");

                    b.ToTable("ResultImageSetTimes");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ImageSet", b =>
                {
                    b.HasOne("UiDesktopApp2.DataAccess.Entities.Test", "Test")
                        .WithMany("ImageSets")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ImageVariant", b =>
                {
                    b.HasOne("UiDesktopApp2.DataAccess.Entities.ImageSet", "ImageSet")
                        .WithMany("ImageVariants")
                        .HasForeignKey("ImageSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageSet");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Result", b =>
                {
                    b.HasOne("UiDesktopApp2.DataAccess.Entities.Subject", "Subject")
                        .WithMany("Results")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UiDesktopApp2.DataAccess.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ResultImageSetTime", b =>
                {
                    b.HasOne("UiDesktopApp2.DataAccess.Entities.ImageSet", "ImageSet")
                        .WithMany()
                        .HasForeignKey("ImageSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UiDesktopApp2.DataAccess.Entities.Result", "Result")
                        .WithMany("ImageSetTimes")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageSet");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.ImageSet", b =>
                {
                    b.Navigation("ImageVariants");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Result", b =>
                {
                    b.Navigation("ImageSetTimes");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Subject", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("UiDesktopApp2.DataAccess.Entities.Test", b =>
                {
                    b.Navigation("ImageSets");
                });
#pragma warning restore 612, 618
        }
    }
}
